import numpy as np
import rasterio
from rasterio.transform import rowcol
import math


# --- Utility Functions -------------------------------------------------------

# global variables
rng = np.random.default_rng(42)  # reproducible random number generator with seed 42.

def open_raster_UTM(src_path):
    """
    Load a raster and reproject to EPSG:4326 (lon/lat).
    Returns (arr, transform, crs), where arr is float32 with NaNs for NoData.
    Optionally set output resolution in degrees via dst_res_deg (e.g., 0.0001).
    """
    if src_path == None:
        print(f"Warning: No path provided for raster {src_path}. Returning None.")
        return None, None, None, None, None, None
    with rasterio.open(src_path) as src:
        src_arr = src.read(1)
        src_transform = src.transform
        src_crs = src.crs
        h, w = src.height, src.width
        src_extent = (src.bounds.left, src.bounds.right, src.bounds.bottom, src.bounds.top)
    return src_arr, src_transform, src_crs, src_extent, h, w

def open_raster_image(src_path):
    with rasterio.open(src_path) as src:
        src_arr = src.read()
    return src_arr

def format_td(td):
    """Function to help formating the timing outputs.
    Removes decimal seconds from the output. (Generated by ChatGPT)"""
    total_seconds = int(td.total_seconds())  # removes decimals
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"

# --- Helper Functions -------------------------------------------------------
def is_water(utm_x, utm_y, MapData):
    """True if point lands on water""" 

    r, c = rowcol(MapData.wm_tfm, utm_x, utm_y, op=round)     # finds the pixel corrosponding to the coordinate
    # Out of bounds is water
    if r < 0 or c < 0 or r >= MapData.wm_arr.shape[0] or c >= MapData.wm_arr.shape[1]:
        return True

    water_check = MapData.wm_arr[r, c] == 1

    return water_check

def height_at_utm(x, y, MapData):
    """
    Function that takes a coordinate location in UTM and find the height value in the DTM.
    """
    if x < MapData.dtm_extent[0] or x > MapData.dtm_extent[1] or y < MapData.dtm_extent[2] or y > MapData.dtm_extent[3]:
        #print("Warning: Coordinate out of bounds for DTM. Returning NaN.")
        return np.nan
    elif np.isnan(x) or np.isnan(y):
        return np.nan
    else:
        row, col = rowcol(MapData.dtm_tfm, x, y, op=int) # find the pixel in the DTM that corrosponds to the coordinates
        height_val = MapData.dtm_arr[row, col]
    return height_val

    
def check_near_road(utm_x, utm_y, MapData):
    """Returns True if point is near road based on buffer distance.
    Returns a bearing to follow when follow road probability is met."""

    # Check if within map extent, if so return not near road.
    if utm_x < MapData.dtm_extent[0] or utm_x > MapData.dtm_extent[1] or utm_y < MapData.dtm_extent[2] or utm_y > MapData.dtm_extent[3]:
        return False
    
    # Check if near road by seeing if the agent is on the road buffer mask.
    r, c = rowcol(MapData.buff_roads_tfm, utm_x, utm_y, op=round)

    # If row and column are out of bounds, return not near road.
    if r < 0 or c < 0 or r >= MapData.buff_roads_arr.shape[0] or c >= MapData.buff_roads_arr.shape[1]:
        return False
    
    road_check = MapData.buff_roads_arr[r, c] == 1

    return road_check

def check_near_road_near(utm_x, utm_y, MapData):
    """Returns True if point is near road based on buffer distance.
    Returns a bearing to follow when follow road probability is met."""

    # Check if within map extent, if so return not near road.
    if utm_x < MapData.dtm_extent[0] or utm_x > MapData.dtm_extent[1] or utm_y < MapData.dtm_extent[2] or utm_y > MapData.dtm_extent[3]:
        return False
    
    # Check if near road by seeing if the agent is on the road buffer mask.
    r, c = rowcol(MapData.roads_tfm, utm_x, utm_y, op=round)

    # If row and column are out of bounds, return not near road.
    if r < 0 or c < 0 or r >= MapData.roads_arr.shape[0] or c >= MapData.roads_arr.shape[1]:
        return False
    
    road_check = MapData.roads_arr[r, c] == 1

    return road_check

def DDA(transform, x0, y0, x1, y1, dda_resolution):

    dx = x1 - x0
    dy = y1 - y0

    if np.isnan(dx) or np.isnan(dy): # If either coordinate is NaN, return empty list (no cells) --> "fell_off_map" blocker should terminate the simulation on the next step.
        steps = 0
    else:
        steps = int(max(abs(dx), abs(dy))/dda_resolution) # 1 step per meter (1×1 raster)

    if steps == 0:
        r, c = rowcol(transform, x0, y0, op=round)
        return [(r, c)]

    x_inc = dx / steps
    y_inc = dy / steps

    cells = []
    prev = None

    x, y = x0, y0
    for _ in range(steps + 1):
        r, c = rowcol(transform, x, y, op=round)
        if prev != (r, c):
            cells.append((r, c))
            prev = (r, c)
        x += x_inc
        y += y_inc

    return cells




